---
title: "Séance 2 : Analyser et visualiser un jeu de données semi-quantitatif"
output: bookdown::html_document2
---

# - Introduction
Nous avons vu à la séance précédente comment parcourir un jeu de données et faire un graphique simple avec le language R de base.  
Au cours de cette séance nous utiliserons les extensions du *package* **tidyverse**. Le terme tidyverse est une contraction de *tidy* (qu’on pourrait traduire par “bien rangé”) et de *universe*. Il s’agit d’une collection d’extensions conçues à partir d'une philosophie commune.
Elles abordent un très grand nombre d’opérations courantes dans R (la liste n’est pas exhaustive):  
- la visualisation  
- la manipulation des tableaux de données  
- l'import/export de données  
- la manipulation de variables  
- l'extraction de données du web  
- la programmation  

L'un des objectifs de ces extensions est de fournir des fonctions avec une syntaxe cohérente, qui fonctionnent bien ensemble, et qui retournent des résultats prévisibles. Elles sont en grande partie issues du travail d’Hadley Wickham.  

Téléchargons et chargons le package tidyverse avec les commandes suivantes
```{r tidyverse, echo=T}
#install.packages("tidyverse")
#library(tidyverse)
```
